org: dyadic
app: receipt-saver-be
service: receipt-saver-be-service

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-2
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    CLIENT_URL: ${self:custom.secrets.CLIENT_URL}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  app:
    handler: build/app.sls.server
    events:
      - http:
          path: /helloWorld
          method: get
          cors: true
  create:
    handler: build/repositories/receipt.create
    events:
      - http:
          path: todos
          method: post
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

custom:
  secrets: ${file(secrets.json)}
#  scriptHooks:
#    before:package:createDeploymentArtifacts: npm run build:client
#   - serverless-offline
