org: dyadic
app: receipt-saver-be
service: receipt-saver-be-service

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-2
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    CLIENT_URL: ${self:custom.secrets.CLIENT_URL}

functions:
  app:
    handler: build/app.sls.server
    events:
      - http:
          path: /helloWorld
          method: get
          cors: true


custom:
  secrets: ${file(secrets.json)}
#  scriptHooks:
#    before:package:createDeploymentArtifacts: npm run build:client
#   - serverless-offline
