org: dyadic
app: receipt-saver-be
service: rs-service

custom:
  defaultEnv: ${file(./config/default_env.json)}
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-2
  environment: 
    NODE_ENV: ${self:custom.defaultEnv.NODE_ENV}
    CLIENT_URL: ${self:custom.defaultEnv.CLIENT_URL}
    TABLE_RECEIPT: ${self:service}-${self:custom.defaultEnv.TABLE_RECEIPT}-${self:provider.stage}
    TABLE_ITEM: ${self:service}-${self:custom.defaultEnv.TABLE_ITEM}-${self:provider.stage}
    TABLE_USERS: ${self:service}-${self:custom.defaultEnv.TABLE_USERS}-${self:provider.stage}
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - { "Fn::GetAtt": ["ReceiptDynamoDBTable", "Arn" ] }

functions:
  app:
    handler: build/app.sls.server
    events:
      - http:
          path: /helloWorld
          method: get
      - http:
          path: /receipt
          method: ANY


resources:
  Resources:
    ReceiptDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TABLE_RECEIPT}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
