Resources:
  ReceiptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.bucketReceiptsName}
      AccessControl: 'PublicReadWrite'
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - ${env:CLIENT_URL}
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
